### ISSUE TITLE
omeka s 4.0

### ISSUE THREAD

**Issue by johnhtx** [biblibre/omeka-s-module-RandomItemsBlock#1]
Error: Random Items Block requires Omeka S ^3.0.0 

my version
[Omeka S](https://omeka.org/s) version 4.0.0 [System information](http://archives.dickinsonhistoricalsociety.org/admin/system-info) [User manual](https://omeka.org/s/docs/user-manual) [Support forums](https://forum.omeka.org/)

**Comment by jajm** [comment]
Just released v0.3.0 which is compatible with Omeka S 3.x and 4.0
